language: android
sudo: required
jdk: 
 - oraclejdk11

dist: trusty
env:
 global:
 - ANDROID_API=31
 - ANDROID_BUILD_TOOLS=30.0.2
 - ADB_INSTALL_TIMEOUT=5
 - ANDROID_HOME=~/android-sdk

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - extra-android-support
 - extra-google-m2repository
 - extra-android-m2repository
 - extra-google-google_play_services

licenses:
  - 'android-sdk-license-.+'
  - '.+'

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${ANDROID_API}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" --sdk_root=$ANDROID_HOME

script:
 - cd MyApp
 - chmod +x gradlew
 - ./gradlew clean
 - ./gradlew detekt ktlintCheck
 - ./gradlew build connectedCheck -PdisablePreDex --stacktrace
 - ./gradlew test --info
